import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <h1>기본 레이아웃 입니다</h1>
        <Link href="/">홈</Link>
        <Link href="/list">리스트</Link>
        {children}
        </body>
    </html>
  )
}


