import "./globals.css";
import { Inter } from "next/font/google";
import { signIn } from "next-auth/react";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import GithubLoginBtn from "./githubLoginBtn";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  console.log("---------------------Session Data Start---------------------");
  const session = await getServerSession(authOptions);
  console.log("session : ", session);
  console.log("---------------------Session Data End---------------------");
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <GithubLoginBtn />
        </div>
        <div>{children}</div>
      </body>
    </html>
  );
}
